name: dcob
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: 8.1.1
  bip39: 1.0.6
  flutter_secure_storage: 7.0.1
  web3dart: 2.5.0
  image_picker: 0.8.6
  ed25519_hd_key: 2.2.0
  hex: 0.2.0
  logger: 1.1.0
  http: 0.13.5
  dart_bip32_bip44: 0.2.0
  webview_flutter: 4.0.0
  qr_flutter: 4.0.0
  path_provider: 2.0.14
  cached_network_image: 3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
     - contracts/abi/abi.json
     - assets/env.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic